import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft } from "lucide-react";
import { BrandMark } from "@/components/BrandMark";

export const Route = createFileRoute("/terms")({
  head: () => ({ meta: [{ title: "Terms of Service — Body Forge" }] }),
  component: Terms,
});

// NOTE FOR THE OWNER: this is a solid starting template written for a
// consumer AI fitness subscription. Have a lawyer review it before launch and
// replace [YOUR BUSINESS NAME] / [JURISDICTION] / the support email.

function Terms() {
  return (
    <LegalShell title="Terms of Service" updated="July 22, 2026">
      <H>1. What Body Forge is</H>
      <P>
        Body Forge ("the Service") is an AI-powered fitness and nutrition coaching app operated by
        [YOUR BUSINESS NAME] ("we", "us"). By creating an account or using the Service you agree to
        these Terms. If you do not agree, do not use the Service.
      </P>

      <H>2. Not medical advice</H>
      <P>
        Body Forge provides automated fitness and nutrition information for general educational
        purposes only. It is not medical advice, diagnosis, or treatment, and the AI coach is not a
        physician, physical therapist, or dietitian. Always consult a qualified healthcare provider
        before starting any exercise or nutrition program, especially if you are pregnant, have an
        injury, or have any medical condition. Never disregard professional medical advice because
        of something the Service said.
      </P>

      <H>3. Assumption of risk</H>
      <P>
        Exercise carries inherent risk of injury. You are responsible for exercising within your
        limits, using proper equipment, and stopping immediately if you feel pain, dizziness, or
        discomfort. To the maximum extent permitted by law, you assume all risk arising from your
        use of any workout, movement, or nutrition suggestion in the Service.
      </P>

      <H>4. AI-generated content</H>
      <P>
        Programs, meal plans, form feedback, and chat responses are generated by artificial
        intelligence. AI can make mistakes. Content is provided "as is" without warranty of
        accuracy, and you should apply your own judgment before acting on it.
      </P>

      <H>5. Accounts</H>
      <P>
        You must be at least 16 years old to use the Service. You are responsible for your account
        credentials and for all activity under your account. Provide accurate information — your
        program is only as good as what you tell your coach.
      </P>

      <H>6. Subscriptions, trials, and refunds</H>
      <P>
        Paid plans renew automatically each billing period until canceled. Free trials convert to a
        paid subscription at the end of the trial unless canceled first. You can cancel anytime from
        your Profile; access continues until the end of the paid period. Unless required by law,
        payments are non-refundable, but if something went wrong, contact support and we will make
        it right where we reasonably can. Prices may change with notice before your next renewal.
      </P>

      <H>7. Acceptable use</H>
      <P>
        Do not misuse the Service: no unlawful use, no attempting to break, overload, or reverse
        engineer it, no scraping other users' data, and no uploading content you do not have the
        right to share. We may suspend accounts that violate these Terms.
      </P>

      <H>8. Your content</H>
      <P>
        You keep ownership of the photos, videos, and information you upload. You grant us the
        limited license needed to operate the Service — for example, sending your form video to our
        AI provider to analyze it and show you the result.
      </P>

      <H>9. Limitation of liability</H>
      <P>
        To the maximum extent permitted by law, our total liability for any claim arising from the
        Service is limited to the amount you paid us in the twelve months before the claim. We are
        not liable for indirect, incidental, or consequential damages, including personal injury
        arising from exercise performed at your own discretion.
      </P>

      <H>10. Changes and termination</H>
      <P>
        We may update the Service and these Terms; material changes will be notified in the app or
        by email, and continued use means acceptance. You may delete your account at any time from
        your Profile. These Terms are governed by the laws of [JURISDICTION].
      </P>

      <H>11. Contact</H>
      <P>Questions about these Terms: support@bodyforge.app (replace with your support address).</P>
    </LegalShell>
  );
}

export function LegalShell({
  title,
  updated,
  children,
}: {
  title: string;
  updated: string;
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-dvh bg-background text-foreground">
      <div className="sticky top-0 z-10 border-b border-border/60 bg-background/85 backdrop-blur-xl">
        <div className="mx-auto flex h-14 max-w-lg items-center gap-3 px-5">
          <Link
            to="/welcome"
            aria-label="Back"
            className="grid h-9 w-9 place-items-center rounded-full bg-surface"
          >
            <ArrowLeft className="h-4 w-4" />
          </Link>
          <BrandMark size={24} />
          <span className="font-display font-extrabold tracking-tight">Body Forge</span>
        </div>
      </div>
      <div className="mx-auto max-w-lg px-5 py-8">
        <h1 className="page-title mb-1">{title}</h1>
        <p className="mb-6 text-xs text-muted-foreground">Last updated {updated}</p>
        <div className="space-y-1">{children}</div>
      </div>
    </div>
  );
}

function H({ children }: { children: React.ReactNode }) {
  return <h2 className="mt-6 mb-1.5 text-base font-bold">{children}</h2>;
}
function P({ children }: { children: React.ReactNode }) {
  return <p className="text-sm leading-relaxed text-muted-foreground">{children}</p>;
}
